version: '3.1'
services:
  api:
    build: .
    command: cargo test
    depends_on:
      - qdrant
    environment:
      - QDRANT_URL=http://qdrant:6333


  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    volumes:
      - ./volumes/qdrant:/qdrant/storage
    ports:
      - "6333:6333"