version: '3.1'
services:
  api:
    build: .
    command: cargo test
    depends_on:
      - embedding-service

  embedding-trainer:
    build: image-text-embedding-service/python.Dockerfile

  vespa:
    build: vespa/vespa.Dockerfile