version: '3.1'
services:
  api:
    build: .
    command: cargo test
    depends_on:
      - embedding-service

  embedding-service:
    build: image-text-embedding-service/.

  vespa:
    image: vespaengine/vespa